from api.v1 import (
    adjacency_matrix,
    algorithms,
    automata,
    calculus,
    chat,
    colab_export,
    combinatorics,
    graph_theory,
    learning_feedback,
    linear_algebra,
    logic,
    number_theory,
    problem_generation,
    problem_templates,
    probability,
    set_theory,
)

ROUTERS = [
    combinatorics.router,
    logic.router,
    set_theory.router,
    automata.router,
    graph_theory.router,
    adjacency_matrix.router,
    probability.router,
    number_theory.router,
    linear_algebra.router,
    algorithms.router,
    calculus.router,
    learning_feedback.router,
    colab_export.router,
    chat.router,
    problem_generation.router,
    problem_templates.router,
]

FEATURE_NAMES = [
    'Graph Theory',
    'Combinatorics',
    'Probability',
    'Automata',
    'Set Theory',
    'Number Theory',
    'Linear Algebra',
    'Algorithms',
    'Calculus',
    'Logic',
    'Learning Feedback',
    'Colab Export',
    'AI Chat',
    'Problem Templates',
    'Problem Generation',
]
